# Compose CI pipeline
x-documentation: >
  Project: hello-compose-ci
  Start the CI pipeline:
  docker compose -f compose.ci.yml up --build

services:
  # Run unit tests
  unit-tests:
    extends:
      file: compose.ci.unit-tests.yml
      service: unit-tests

  multi-arch-build-application:
    extends:
      file: compose.ci.multi-arch-build-application.yml
      service: multi-arch-build-application
    
    depends_on:
      unit-tests:
        condition: service_completed_successfully

  # Deploy the function (locally) for testing
  start-service-for-local-testing:
    extends:
      file: compose.ci.start-service-for-local-testing.yml
      service: start-service-for-local-testing
        
    depends_on:
      multi-arch-build-application:
        condition: service_completed_successfully

  # Test the endpoint
  test-home-endpoint:
    extends:
      file: compose.ci.test-home-endpoint.yml
      service: test-home-endpoint
      
    depends_on:
      start-service-for-local-testing:
        condition: service_healthy

  # Stress test the endpoint
  stress-test:
    extends:
      file: compose.ci.stress-test.yml
      service: stress-test
    depends_on:
      test-home-endpoint:
        condition: service_completed_successfully        

  # Stop the function after testing
  stop-web-service:
    extends:
      file: compose.ci.stop-web-service.yml
      service: stop-web-service

    depends_on:
      stress-test:
        condition: service_completed_successfully

  # Create a multi architecture image
  build-local-image:      
    extends:
      file: compose.ci.build-local-image.yml
      service: build-local-image

    depends_on:
      stop-web-service:
        condition: service_completed_successfully
  
  start-container-from-local-image:
    extends:
      file: compose.ci.build-local-image.yml
      service: start-container-from-local-image
    # dependencies are defined in the extended file
  stop-container-from-local-image:
    extends:
      file: compose.ci.build-local-image.yml
      service: stop-container-from-local-image
    # dependencies are defined in the extended file
  
  image-analysis:
    extends:
      file: compose.ci.image-analysis.yml
      service: image-analysis

    depends_on:
      stop-container-from-local-image:
        condition: service_completed_successfully


  build-publish-image:
    profiles: [ publish-image ]
    extends:
      file: compose.ci.build-publish-image.yml
      service: build-publish-image
    depends_on:
      image-analysis:
        condition: service_completed_successfully