services:

  start-service-for-local-testing:
    labels:
      local.service: start-service-for-local-testing
    image: ubuntu:22.04
    environment:
      TARGETOS: linux
      TARGETARCH: arm64    
    volumes:
      - ./builds:/builds      
    command:       
      - /bin/sh
      - -c
      - |  
        apt-get update && apt-get install -y wget
        echo "🚀 Starting the service locally on port 8080"
        chmod +x ./builds/hello-$${TARGETOS}-$${TARGETARCH}
        ./builds/hello-$${TARGETOS}-$${TARGETARCH}

    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 40s